//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCrud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }

        [Display(Name ="Employee Name")]
        public string EmpName { get; set; }
        [Display(Name ="Employee Salary")]
        public Nullable<decimal> EmpSalary { get; set; }
        [Display(Name ="Employee Mail Id")]
        public string Email { get; set; }
    }
}
